### ISSUE TITLE
Replace the web application (vuejs base) with regular HTML5/JS/CSS to save space.

### ISSUE THREAD

**Issue by BlueAndi** [NewTec-GmbH/ZumoComSystem#90]
The vuejs is a way to huge and prevents further features.

Use bootstrap for responsive design.

**Comment by gabryelreyes** [comment]
Is replacing the web application still planned? Or should we use the ZIP-File alternative?

Current total size of data/files sent to the client: 862 kB
Size of a ZIP containing all the mentioned files: 247 kB

**Comment by BlueAndi** [comment]
The bootstrap approach may still need 4 times less space if its gzipped compared to the gzipped vuejs app.

**Comment by gabryelreyes** [comment]
API Commands to Implement:
- [ ] getfirmwareinfo
- [ ] authenticate
- [ ] deauthenticate
- [ ] uploadzumo (Text)
- [ ] uploadzumo (Binary)
- [ ] uploadcom (Text)
- [ ] uploadcom (Binary)
- [ ] rebootzumo
- [ ] rebootcom
- [ ] flashzumo
- [ ] flashcom
- [ ] setstacredentials
- [ ] echodemo

**Comment by gabryelreyes** [comment]
Application is functional.
 
(Possible) To-Do's:
- Beautify Alerts/Notifications/Modals
- Autocomplete Login Credentials
- Progress bar for uploading and flashing firmware
- Notifiication when connected to Server
- Signing of Firmware using private key (Current Status: only accepting CPSFW Files)
